### ISSUE TITLE
Attribute dependent styles can't be mixed

### ISSUE THREAD

**Issue by AnnaMoudra** [MetacitySuite/BananaGL#37]
We should allow mixing of styles based on multiple attribute values.
`
styles: [
gl.style.withAttributeEqualTo("ATTRIB", 1).useColor(0x00FF00),
gl.style.withAttributeEqualTo("ATTRIB", 2).useColor(0x0000FF)
]
`

**Comment by vojtatom** [comment]
Should be resolved when https://github.com/MetacitySuite/BananaGL/pull/41 is included in release, pending

**Comment by vojtatom** [comment]
Fix included in release [v1.1.0](https://github.com/MetacitySuite/BananaGL/releases/tag/v1.1.0), please confirm

**Comment by AnnaMoudra** [comment]
Fix confirmed :ant:
